# Generated by Django 3.1.7 on 2021-04-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0002_auto_20210417_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='app_services'),
        ),
    ]
